### ISSUE TITLE
Improve the release workflow

### ISSUE THREAD

**Issue by dbierek** [glacier-modding/NavKit#4]
The release github workflow should:
* Create a release file when a new tag is pushed
* The release file should only contain files needed for the release

Use something like this:
```yml
name: Release Build

on:
  push:
    tags:
      - 'v*' # Trigger on any tag starting with 'v' (e.g., v1.0, v2.5.3)

jobs:
  build:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest, depending on your needs

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawrence/cmake-github-action@v2
        with:
          cmake_args: -DCMAKE_BUILD_TYPE=Release # Important: Set build type to Release

      - name: Build Release
        run: cmake --build build --config Release # Build in Release configuration

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} # Use the pushed tag as the release tag
          release_name: Release ${{ github.ref }} # Give the release a name (optional)
          body: |
            Automated Release for ${{ github.ref }}

            Add release notes here (optional).

      - name: Upload Release Assets (Optional)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/MyExecutable # Path to your executable (adjust as needed)
          asset_name: MyExecutable-${{ github.ref }}.exe # Name of the asset (adjust as needed)
          asset_content_type: application/octet-stream # Or appropriate content type
```
